### PR TITLE
AF-2542: GWT 2.9 upgrade

### PR DESCRIPTION
**Pull request by porcelli**
**JIRA**: [AF-2542](https://issues.redhat.com/browse/AF-2542)

**referenced Pull Requests**: 

* https://github.com/kiegroup/lienzo-core/pull/122
* https://github.com/kiegroup/lienzo-tests/pull/103
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1442
* https://github.com/kiegroup/appformer/pull/1030
* https://github.com/kiegroup/drools/pull/3051
* https://github.com/kiegroup/kie-wb-common/pull/3395
* https://github.com/kiegroup/drools-wb/pull/1412

### CODE REVIEW

**Review by hasys — APPROVED** [review]
Looks good to me, thank you @porcelli

**Comment by mbiarnes** [comment]
closed accidentally

**Comment by mbiarnes** [comment]
JAVA11-test

**Comment by mbiarnes** [comment]
JAVA11-test

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
closing as there is https://github.com/kiegroup/lienzo-core/pull/134 as a replacement

**Pull request closed without merging**
