### PR TITLE
JBPM-6883 Stunner - can't move with bend points - setting drag bounds

### PR DESCRIPTION
**Pull request by tiagodolphine**
Now it is now possible to move bend points of a connector outside of the canvas area.
It was necessary to set the drag bounds of the connector point handles.

@LuboTerifaj
@wmedvede (adding you to help on the review since @romartin is on PTO)

related: 
https://github.com/kiegroup/kie-wb-common/pull/2012
https://github.com/kiegroup/lienzo-tests/pull/39

### CODE REVIEW

**Comment by wmedvede** [comment]
Hello @tiagodolphine  I've built this PR locally and rebased with master, etc. And the fix works.
The effect of not letting the bendpoints to be moved outside the canvas is working well.

One quick note I could see (I don't remember how it worked before and probably it's something for discussion). But in general when you are dragging both a "bendpoint" or a "node", when the node is dragged outside of the canvas, the dragging is stopped, this good since we don't want the node to be moved outside the canvas. Buy if you keep the mouse pressed, and return the mouse pointer to the canvas again, the node was left.

See the video https://youtu.be/I-C0zCkBe0M  

It could probably be nice to: "if the user keeps the mouse button pressed" when the mouse returns to the canvas area, the originally dragged node could continue dragging.
I believe this could be nice because in case the user by mistake moves the node to the boundaries of the canvas he we'll probably return to the canvas area. Specially in cases where there are still room in the canvas, e.g. if the "View area" is in the middle of the canvas.

**Comment by tiagodolphine** [comment]
hi @wmedvede thanks for the review!
Yeah I agree with you, regarding the drag to continue when the mouse is back to canvas area, we can open a JIRA for this improvement since it is not related to this PR, WDYT ? @LuboTerifaj  @hasys what is your opinion?

**Comment by hasys** [comment]
Hi @tiagodolphine @wmedvede,

yes, I guess it's better to open a new Jira for it.

**Comment by tiagodolphine** [comment]
Hi @LuboTerifaj I think this one is missing for approval/review you already reviewed the kiegroup/kie-wb-common#2012

**Comment by hasys** [comment]
Hi @manstis this is related to https://github.com/kiegroup/kie-wb-common/pull/2012 PR and also ready to merge.

**Comment by manstis** [comment]
@hasys Please let me know when the full downstream on #2012 completes. Thanks.

**Pull request merged**
