### PR TITLE
Color.toBrowserRGBA alpha fix

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin; 
This is an important fix cherry-picked from  https://github.com/dikalo/lienzo-core/pull/225/files.

Could you review this PR Please?

Thanks

### CODE REVIEW

**Comment by handreyrc** [comment]
Jenkins run fdb

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
@LuboTerifaj or @domhanak  - do you want to review this before merging? Thx!

**Comment by LuboTerifaj** [comment]
Hi @romartin , I don't see any jira linked here. I am not sure what is the point of the change, but it seems like the reasonable change.

**Comment by domhanak** [comment]
Hi @romartin @handreyrc  Not sure what to test, I would like to see FDB pass, other than that is seems ok.
Maybe we can add additonal test case to check corner cases with `final double a`. What should be the output when I use `a=0.51`? Is the expected ouput `0.5`?

**Comment by domhanak** [comment]
Jenkins run fdb

**Comment by mbiarnes** [comment]
Jenkins run fdb

**Comment by domhanak** [comment]
@romartin @handreyrc fdb not passing, please chekc my comment

**Comment by handreyrc** [comment]
Hey @domhanak, this is very hard to test and there are good chances we are not be using it. However, the color scheme parameter is clearly wrong and should be fixed.

By the way, this PR is a bit old I'll rebase and fire the builds. 

What do you think?
CC @romartin

**Comment by manstis** [comment]
Let's agree to merge "as is"... it's an obvious simple fix.

**Comment by handreyrc** [comment]
Jenkins run fdb

**Review by domhanak — APPROVED** [review]

**Comment by handreyrc** [comment]
Jenkins run fdb

**Comment by handreyrc** [comment]
jenkins do fdb

**Comment by domhanak** [comment]
cc @romartin

**Pull request merged**
