### PR TITLE
JBPM-8132: Stunner - selected objects can't be moved more than one ti…

### PR DESCRIPTION
**Pull request by treblereel**
…me without reselection
JIRA: https://issues.jboss.org/browse/JBPM-8132
@mdproctor may i ask you to take a look ?

before

result:
after

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by treblereel** [comment]
hmmm,

FAILURE: Build failed with an exception.
* Where:
Build file '/home/travis/build/kiegroup/lienzo-core/build.gradle' line: 121
* What went wrong:
A problem occurred evaluating root project 'lienzo-core'.
> Could not get unknown property 'sonatype_stageingURL' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

**Comment by hasys** [comment]
Jenkins retest please

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @treblereel,

looks good, but missing unit test. I prepared an example how can you test it. 
See `SelectionManagerTest#testDoNotCleanSelectionForNodeDuringSelectionMove` method here: https://github.com/hasys/lienzo-tests/commit/41b7ced312b9caacb8e682c53829c6b11f662977
(it is not the final version, but all setup is done, so you can just finish it and write addition tests if needed).

ping @romartin

**Comment by treblereel** [comment]
Jenkins execute full downstream build

**Pull request merged**
