### PR TITLE
Disable blue border around canvas in Google Chrome

### PR DESCRIPTION
**Pull request by hasys**
Hi @romartin, @pefernan, @manstis 

here is a fix for blue border around canvas. Let me know if you know better way to do so.

I will try to find a way how to disable for Widgets as well.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Sent PR to Appformer to fix all blue borders in Chrome. See https://github.com/kiegroup/appformer/pull/210 (This Downstream build will contain fix only for Canvas). Both changes can be tested here: https://github.com/kiegroup/appformer/pull/210

**Comment by romartin** [comment]
@manstis @jomarko adding you as reviewers as well, not sure if this could have implications on dmn or decision tables...

**Comment by romartin** [comment]
@hasys @manstis You think can this be done in the `LienzoPanel` widget? I mean doing this in the `LienzoCore` class seems too "generic".. isn't it? Could we focus this style just on the concrete widget class? Makes sense?

**Comment by manstis** [comment]
I agree with @romartin comment about not really wanting to add this to ```LienzoCore```.

DMN would (in part) inherit the change - as it uses Stunner for the "graph editing" however it would need a similar change in ```appformer\uberfire-extensions\uberfire-wires\uberfire-wires-core\uberfires-wires-core-grids``` as the "table editing" uses ```GridLienzoPanel```.

**Comment by hasys** [comment]
Hi @romartin, @manstis

yes, sound good. LienzoPanel looks much better here.

P.S. Just realized that Stunner has 4 canvases. Is it expected?
image

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by jomarko** [comment]
@romartin DMN is definitely affected, thanks for marking me, however I will do review tomorrow morning, today it is not manageable for me.

**Comment by hasys** [comment]
It looks like removed unused private local field somehow in use. Looking. Don't merge it, please.

**Comment by hasys** [comment]
It is kind of JavaScript magic, but unused private field in LienzoPanel class is in use somehow. I reverted changes around this property, only blue borders disabling code now in this PR.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @romartin @manstis @jomarko @ederign,

I tested locally this Full Downstream Build and it looks good to me. Let me know if I missed something.

**Comment by romartin** [comment]
> P.S. Just realized that Stunner has 4 canvases. Is it expected?
Yes, it's Lienzo internals. It uses canvas elements to address multi-layers.. in fact I was remembering only 3, not 4, anyway it's nothing about stunner itself.

**Comment by jomarko** [comment]
- DMN is still affected, pictures below
- Guided decision tables are ok

screenshot from 2018-03-02 09-54-13
screenshot from 2018-03-02 09-57-45

**Comment by manstis** [comment]
@jomarko @hasys See https://github.com/kiegroup/lienzo-core/pull/9#issuecomment-369374736

**Comment by jomarko** [comment]
@manstis I have no preference. My knowledge of codebase is not enough to asses possible impact of the decision, however I can definitely check the change we agree on manually.

**Comment by manstis** [comment]
@romartin I chatted to @hasys about this PR.. I am concerned that the ```outline:none``` change should not be in ```ahome-it/lienzo-core``` but in reality (a) IDK if our fork is to ever be merged back to Dean Jones' (b) Dean Jones may not care/may like the changre anyway!

So @romartin I will leave the final decision with you :-)

**Comment by hasys** [comment]
Hi @romartin, @manstis,

complications is a copy paste this line of code between of all existing and future editors based on LienzoPanel. But if I correct the only benefit of it is a possibility of merge our changes with Upstream, but not sure if our fork is compatible after removed `event.preventDefault`. So, the only benefit is not actual any more, in my opinion. 

But if you think it is still better to copy/paste this property everywhere, I will do it, no problem.

**Comment by romartin** [comment]
hey @hasys , well the thing is that removing the event.preventDefault IMO makes sense, but applying the outline style seems something more browser or environment specific, I mean it happens on actual Stunner editors due to all the widgets there are in the same page and listening for events, but probably in other situations this style is not the right one or does not makes sense... 
Well anyway this bug is doing some noise so I'm agree on merging this as it is, we can just move it if necessary in the future. So just need now @jomarko  approval. to ensure it works on DMN. Once approved will merge.
Thanks!

**Pull request merged**
