### PR TITLE
Release fixbb

### PR DESCRIPTION
**Pull request by mdproctor**

### CODE REVIEW

**Comment by romartin** [comment]
Hey @hasys 
This improvement from @mdproctor is really good, it works fine and it goes faster, I've already tested... can you please give it a try and add your review?

Thanks!

**Comment by mdproctor** [comment]
The current curve BB code is large, buggy and heavily recursive making it slow. This replaces it with a light weight version taken from https://stackoverflow.com/questions/2587751/an-algorithm-to-find-bounding-box-of-closed-bezier-curves/14429749#14429749
Separately I have emailed a visual inspection test, that was also from a link in that thread.

The PR includes two commits related to precision errors, as this code needs that too.

**Comment by romartin** [comment]
cherry-picked to `7.7.x` -> see https://github.com/kiegroup/lienzo-core/pull/39

**Comment by romartin** [comment]
Hey @hasys 
This work is the same task already cherry-picked into `7.7.x`, see https://github.com/kiegroup/lienzo-core/pull/39 
It improves the performance and it has to be merged to keep `master` up to date  as well, can you please add your review?
I've tested and works fine.
Thanks!

**Comment by hasys** [comment]
There are no business-central to test, let's try again.
Jenkins execute full downstream build

**Comment by romartin** [comment]
@hasys the full downstream fails due to some unrelated tests

**Comment by hasys** [comment]
Hi @romartin,

it looks like there are no way to check business central in this repository (see built artifacts below). Is it correct @mareknovotny?
image

**Comment by hasys** [comment]
@romartin Also, since we are not in GA fewer any more, I guess it will be nice to provide some tests for this code, because test-coverage of lienzo-core is not sufficient and it is very buggy at the same time.

**Comment by romartin** [comment]
Hey @hasys
Yeah I also noticed the downstream builds for this module are not generating the war distributions, as other modules do.... not really sure why doesn'i work, any ideas @mareknovotny @mbiarnes ??
Thanks!

**Comment by romartin** [comment]
Hey @hasys @mdproctor 
Closing just because I'm adding some tests about the BB calculations for paths, including curves. So reopening this into a new PR - https://github.com/kiegroup/lienzo-core/pull/40 (it keeps original commits!)

**Pull request closed without merging**
