### PR TITLE
DROOLS-3427  [DMN Designer] Connections between nodes throws an error if user moves the mouse too fast

### PR DESCRIPTION
**Pull request by danielzhe**
drools3427

### CODE REVIEW

**Comment by danielzhe** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
I'll let @romartin review this (and IIRC there was an email from him somewhere about this), but IMO this masks the issue by simply preventing the NPE from occurring. Is the problem not that `WiresMagnetsControl` has been set to `null` _prematurely_ that leads to the NPE? I'd suspect that an animation hiding the control is setting the control to `null` when the animation starts and not when it ends?

**Comment by danielzhe** [comment]
Yes, I'm investigating further to see the real cause. This is to make it stop to give the error to the user, as @romartin and I discussed.

**Comment by romartin** [comment]
thanks @danielzhe @manstis 
Yeah as commented, we also did "quick" this fix before, but it was due to an urgency... so let's try now, that we have a few more time, to research and figure out the root issue :+1:

**Pull request closed without merging**
