### PR TITLE
Small cleanup and refactoring

### PR DESCRIPTION
**Pull request by hasys**
* fixing string comparision
* clean up code moved to appropriate position
* removed commented code
* removed unused imports
* curly braces located to new line for compatibility with upstream

tests for this PR are provided here https://github.com/kiegroup/lienzo-tests/pull/49

### CODE REVIEW

**Comment by hasys** [comment]
Hi @romartin,

will try to do this clean up sessions as weekly tradition for myself. Please tell if it is not a good idea and it's better to make one but global clean up session and do not send many small changes.

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @jhrcek,

relatively fresh (just 2 days old) test fail in full downstream build:

<details>
  <summary>
org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest.testSLAonProcessViolated[1: JSON KieServicesConfiguration{transport=REST, serverUrl='http://localhost:38977/kie-server-services/services/rest/server'}]</summary>
  <pre>Error Message
Unexpected HTTP response code when requesting URI 'http://localhost:38977/kie-server-services/services/rest/server/containers/definition-project/tasks/1229/states/completed?auto-progress=true'! Error code: 500, message: "Unexpected error during processing: Unable to commit transaction"
Stacktrace
org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://localhost:38977/kie-server-services/services/rest/server/containers/definition-project/tasks/1229/states/completed?auto-progress=true'! Error code: 500, message: "Unexpected error during processing: Unable to commit transaction"
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.createExceptionForUnexpectedResponseCode(AbstractKieServicesClientImpl.java:617)
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPutRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:379)
	at org.kie.server.client.impl.AbstractKieServicesClientImpl.makeHttpPutRequestAndCreateCustomResponse(AbstractKieServicesClientImpl.java:357)
	at org.kie.server.client.impl.UserTaskServicesClientImpl.completeAutoProgress(UserTaskServicesClientImpl.java:118)
	at org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest.testSLAonProcessViolated(SLAComplianceIntegrationTest.java:79)
Standard Output
23:20:44.672 [main] INFO  org.codehaus.plexus.PlexusContainer - Installing /home/jenkins/workspace/KIE/master/pullrequest/lienzo-core-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/target/test-classes/kjars-sources/common-parent/pom.xml to /home/jenkins/.m2/repository/org/kie/server/testing/common-parent/1.0.0.Final/common-parent-1.0.0.Final.pom
23:20:45.262 [main] INFO  o.c.p.compiler.javac.JavacCompiler - Compiling 1 source file to /home/jenkins/workspace/KIE/master/pullrequest/lienzo-core-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/target/test-classes/kjars-sources/definition-project/target/classes
23:20:45.409 [main] INFO  o.c.plexus.archiver.jar.JarArchiver - Building jar: /home/jenkins/workspace/KIE/master/pullrequest/lienzo-core-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/target/test-classes/kjars-sources/definition-project/target/definition-project-1.0.0.Final.jar
23:20:45.440 [main] INFO  org.codehaus.plexus.PlexusContainer - Installing /home/jenkins/workspace/KIE/master/pullrequest/lienzo-core-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/target/test-classes/kjars-sources/definition-project/target/definition-project-1.0.0.Final.jar to /home/jenkins/.m2/repository/org/kie/server/testing/definition-project/1.0.0.Final/definition-project-1.0.0.Final.jar
23:20:45.441 [main] INFO  org.codehaus.plexus.PlexusContainer - Installing /home/jenkins/workspace/KIE/master/pullrequest/lienzo-core-downstream-pullrequests/downstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/target/test-classes/kjars-sources/definition-project/pom.xml to /home/jenkins/.m2/repository/org/kie/server/testing/definition-project/1.0.0.Final/definition-project-1.0.0.Final.pom</pre>
</details>

**Comment by jhrcek** [comment]
Given the history of failures from this test class, it looks like one of the "traditional ones" :)
http://janhrcek.cz/random-failures/#/class/org.kie.server.integrationtests.jbpm.SLAComplianceIntegrationTest

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Pull request merged**
