### PR TITLE
Choose maven over Gradle in Travis CI

### PR DESCRIPTION
**Pull request by hasys**

### CODE REVIEW

**Comment by hasys** [comment]
Hi @romartin, @rsynek I fixed `.travis.yml` to use Maven over Gradle, since Gradle is default build system in Travis CI but we don't update it much.

@rsynek I see as a next step to configure this repo to send every PRs to check with Sonar Cloud. Do you have an experience in this area?

@romartin since we do not use Gradle and it looks like it is not in up to date state any more, can we just delete it entirely?

**Comment by rsynek** [comment]
@hasys sure, please see:
https://github.com/kiegroup/optaweb-employee-rostering/blob/master/.travis.yml
https://github.com/kiegroup/optaweb-employee-rostering/blob/master/travis-sonarcloud.sh
the script handles the differences between nightly build of master branch and a PR build.

Please note, though, that during experimenting with SonarCloud and Travis I found so many limitations, that any new repository I am going to configure the SonarCloud analysis for, the build will run on Jenkins.

**Comment by hasys** [comment]
Hi @rsynek,

thank you, will postpone PR based Sonar Cloud configuration till Jenkins based prototype will be ready.

@romartin any way this PR is ready to go, at least Travis CI will be green.

**Comment by romartin** [comment]
Hey @hasys 
Agree on this change, also agree on deleting the whole Travis/Gradle stuff from here, so up to you, do you want me to merge this as it is or you want to try deleting the file/s as well?
Thanks for your help anyway!! :+1:

**Comment by hasys** [comment]
Hi @romartin, @LuboTerifaj,

I removed Travis and Eclipse related (analog `.idea` for IntelliJ Idea) files as discussed above.

Thank you!

**Comment by hasys** [comment]
Sorry, for spam, I rebased to master and updated commit message with `gradle`, since I removed it's settings as well.

**Comment by romartin** [comment]
great, thanks for this @hasys ! Could you please also do same cleans for our [KIE lienzo-tests](https://github.com/kiegroup/lienzo-tests) module, if you think it also makes sense? If so, we can merge both together..

**Comment by hasys** [comment]
Hi @romartin, good point. I created a PR for the `lienzo-tests` repository as well: https://github.com/kiegroup/lienzo-tests/pull/74 Thank you!

**Comment by romartin** [comment]
Thanks @hasys , waiting for @rsynek review and once done will merge :+1:

**Comment by rsynek** [comment]
@romartin no need to wait for me, I just offered a piece of advice regarding SonarCloud PR analysis. Since I am not at all familiar with lienzo-core, I cannot tell if the cleanup in this PR is right or not.

**Pull request merged**
