### PR TITLE
JBPM-8386: Stunner - Preview mediator does nothing for small selection areas.

### PR DESCRIPTION
**Pull request by romartin**
Hey @tiagobento 

Here is the fix for the preview area mediator, see [JBPM-8386](https://issues.redhat.com/browse/JBPM-8386)

Assembly with https://github.com/kiegroup/lienzo-tests/pull/83

Thannks!

### CODE REVIEW

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @tiagobento 

Attached demo video, see [this comment](https://issues.redhat.com/browse/JBPM-8386?focusedCommentId=14001459&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14001459)

Thanks!

**Comment by tiagobento** [comment]
@romartin I don't think I can review the code itself, but I really like how the feature is working now.

**Comment by romartin** [comment]
Hey @manstis 

You know if those test failures could be related to this fix on mediators? 

https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/lienzo-core-downstream-pullrequests/3/#showFailuresLink

Thanks!

**Comment by manstis** [comment]
I doubt it @romartin.. @jomarko could it be related to recent changes for the target CI server?

**Comment by jomarko** [comment]
I hope is fixed by https://github.com/kiegroup/kie-jenkins-scripts/pull/713

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
@romartin my apology for failing full d. build. It is caused due to no-showcase profile that is activated during full d. build. That profile skip gwt compilation and that is why screenshots are empty. Because selenium tests try to open empty/non-working page.

This PR should fix it. https://github.com/kiegroup/kie-wb-common/pull/3243

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by romartin** [comment]
Hey @jomarko 

Thanks, now the build fails due to an unrelated test failue in org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT (see [unrelated errors](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/lienzo-core-downstream-pullrequests/7/testReport/junit/org.kie.bc/DeploymentIT/org_kie_bc_DeploymentIT/))

I've tested the generated WAR and it works. Merging.

Thanks guys for your collaboration!

**Pull request merged**
