### PR TITLE
JBPM-7715 (Stunner) - Align and distributions are shown incorrectly for the first alignment

### PR DESCRIPTION
**Pull request by Josephblt**
https://issues.jboss.org/browse/JBPM-7715

Diagram's child element attribute changes weren't been listened to.
This fixes it.

### CODE REVIEW

**Comment by Josephblt** [comment]
Hey @hasys, @tiagodolphine. If you guys could please review this. I'd be glad.
@tiagodolphine this changes code you created for docking events (https://github.com/kiegroup/lienzo-core/commit/2b52441aaa472902bbbfb0eb67a0da8bc625868d#diff-9b03ace4f6cfa7fd88241360689500b2). I didn't find any problems with my tests. If you could try it I'd appreciate. Thanks.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Hi @Josephblt, sorry I have a question to @tiagodolphine about this change before merge:

@tiagodolphine what `boolean useChangeListener` is used for? It looks like method `public AlignAndDistributeControl addShape(IDrawable<?> group, boolean useChangeListener)` called twice and true for both invocations. Can we entirely remove this parameter and always add Bounding Box Attributes?

Did I miss something related to boundary events?

**Comment by Josephblt** [comment]
Hey @tiagodolphine. Yes, I agree. I think we can remove it without problems.

**Comment by Josephblt** [comment]
Hey guys (@tiagodolphine, @hasys). Add test and removed the unnecessary method overload. If you guys could review and merge it I'd be glad.

**Comment by Josephblt** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@mdproctor do you want to take a look at this code or can we go ahead?

**Comment by romartin** [comment]
Hey @Josephblt @hasys 
Please can you upload the WAR file somewhere so me and @mdproctor can test the A&D works as expected? I mean the WAR that includes all necessary - both https://github.com/kiegroup/lienzo-core/pull/60 and https://github.com/kiegroup/lienzo-core/pull/61 etc
Thanks!

**Comment by Josephblt** [comment]
Hey @romartin here is a link with the .WAR
https://drive.google.com/open?id=1VUni06ut7S5NM6VTU15WBXjMEX5MXNFt

**Comment by romartin** [comment]
> Hey @romartin here is a link with the .WAR
> https://drive.google.com/open?id=1VUni06ut7S5NM6VTU15WBXjMEX5MXNFt

Hey @Josephblt , please can you make it public? Thx

**Pull request merged**
