### PR TITLE
AF-1799: Upgrade JDK 11 + GWT 2.9

### PR DESCRIPTION
**Pull request by caponetto**
**Upgrade JDK 11 + GWT 2.9**

Feel free to comment and/or raise any concerns.

This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039

Thanks guys for that!

**JIRA**:

[AF-1799](https://issues.redhat.com/browse/AF-1799)

**Referenced Pull Requests**:
- https://github.com/errai/errai/pull/408 [**merged**]
- https://github.com/kiegroup/lienzo-core/pull/134 [**approved**]
- https://github.com/kiegroup/lienzo-tests/pull/109 [**approved**]
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1488 [**approved**]
- https://github.com/kiegroup/kie-soup/pull/161 [**approved**]
- https://github.com/kiegroup/appformer/pull/1059 [**approved**]
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/469 [**approved**]
- https://github.com/kiegroup/drools/pull/3135 [**approved**]
- https://github.com/kiegroup/jbpm/pull/1770 [**approved**]
- https://github.com/kiegroup/kie-jpmml-integration/pull/44 [**approved**]
- https://github.com/kiegroup/droolsjbpm-integration/pull/2259 [**approved**]
- https://github.com/kiegroup/kie-wb-playground/pull/98 [**approved**]
- https://github.com/kiegroup/kie-wb-common/pull/3446 [**approved**]
- https://github.com/kiegroup/drools-wb/pull/1430 [**approved**]
- https://github.com/kiegroup/optaplanner-wb/pull/384 [**approved**]
- https://github.com/kiegroup/jbpm-designer/pull/894 [**approved**]
- https://github.com/kiegroup/jbpm-work-items/pull/162 [**approved**]
- https://github.com/kiegroup/jbpm-wb/pull/1464 [**approved**]
- https://github.com/kiegroup/kie-wb-distributions/pull/1068 [**approved**]

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins execute fdb

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
JAVA11-test

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins execute cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins retest this

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run fdb

**Comment by caponetto** [comment]
Jenkins run cdb

**Review by yesamer — APPROVED** [review]

**Review by Srihari1192 — APPROVED** [review]

**Review by romartin — APPROVED** [review]

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins do fdb

**Pull request merged**
